name: Sofware-Tools

on:
  push:
    branches:
      - main
      
  schedule:
    - cron: "2 * 3 * *"

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
        with:
          persist-credentials: false
          fetch-depth: 0
          
      - name: Run Bot Task
        run: |
          chmod +x ./root.sh
          ./root.sh
          
      - name: GitHub Push
        uses: semgrep-action
  uses: returntocorp/semgrep-action@v1
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
